markdown: rdiscount
permalink: /:year/:month/:day/:title/
url: http://espuppet.github.io
name: 逃跑的木偶
author: espuppet
duoshuo: espuppet
github: espuppet
pygments: true
safe: true
paginate: 15
about: ""
show_drafts: false
